### ISSUE TITLE
AUTHRESPONSE is already defined in argument scope.

### ISSUE THREAD

**Issue by JamoCA** [akitogo/cbYubikey#2]
When I attempted to use it as a CFC for the first time using ColdFusion 2016u15, I received the following CF error:

```
AUTHRESPONSE is already defined in argument scope.
Use local to define a local variable with same name.
<cfset yubicoObj = createObject("Component","cbYubiKey.yubicoAuthClient").init() />
```

The `parseAuthResponse` function in the YubicoAuthClient.cfc file already has an `authResponse` argument and a local variable cannot use the same, duplicate variable name.

I fixed it by changing this:
```
var authResponse = reReplace( arguments.authResponse, "\s",",", "all" );
var aryAuthResp = listToArray( authResponse );
```

to this:
```
var aryAuthResp = listToArray( javacast("string", arguments.authResponse).replaceAll("\s",",") );
```

**Comment by GunnarLieb** [comment]
Thanks James for reporting that issue. It's fixed now
